; This file is auto-generated by codegen. Don't modify it directly
; Either modify the opcode db or the generation logic in codegen
; These strings are used by the disassembler (produced by -s)

	; opcode strings
	.a00 db "0x00   NOP    ",0
	.a01 db "0x01   LD     BC, 0x%02x%02x",0
	.a02 db "0x02   LD     (BC), A",0
	.a03 db "0x03   INC    BC",0
	.a04 db "0x04   INC    B",0
	.a05 db "0x05   DEC    B",0
	.a06 db "0x06   LD     B, 0x%02x",0
	.a07 db "0x07   RLCA   ",0
	.a08 db "0x08   LD     (0x%02x%02x), SP",0
	.a09 db "0x09   ADD    HL, BC",0
	.a0a db "0x0a   LD     A, (BC)",0
	.a0b db "0x0b   DEC    BC",0
	.a0c db "0x0c   INC    C",0
	.a0d db "0x0d   DEC    C",0
	.a0e db "0x0e   LD     C, 0x%02x",0
	.a0f db "0x0f   RRCA   ",0
	.a10 db "0x10   STOP   0",0
	.a11 db "0x11   LD     DE, 0x%02x%02x",0
	.a12 db "0x12   LD     (DE), A",0
	.a13 db "0x13   INC    DE",0
	.a14 db "0x14   INC    D",0
	.a15 db "0x15   DEC    D",0
	.a16 db "0x16   LD     D, 0x%02x",0
	.a17 db "0x17   RLA    ",0
	.a18 db "0x18   JR     0x%02x",0
	.a19 db "0x19   ADD    HL, DE",0
	.a1a db "0x1a   LD     A, (DE)",0
	.a1b db "0x1b   DEC    DE",0
	.a1c db "0x1c   INC    E",0
	.a1d db "0x1d   DEC    E",0
	.a1e db "0x1e   LD     E, 0x%02x",0
	.a1f db "0x1f   RRA    ",0
	.a20 db "0x20   JR     NZ, 0x%02x",0
	.a21 db "0x21   LD     HL, 0x%02x%02x",0
	.a22 db "0x22   LD     (HL+), A",0
	.a23 db "0x23   INC    HL",0
	.a24 db "0x24   INC    H",0
	.a25 db "0x25   DEC    H",0
	.a26 db "0x26   LD     H, 0x%02x",0
	.a27 db "0x27   DAA    ",0
	.a28 db "0x28   JR     Z, 0x%02x",0
	.a29 db "0x29   ADD    HL, HL",0
	.a2a db "0x2a   LD     A, (HL+)",0
	.a2b db "0x2b   DEC    HL",0
	.a2c db "0x2c   INC    L",0
	.a2d db "0x2d   DEC    L",0
	.a2e db "0x2e   LD     L, 0x%02x",0
	.a2f db "0x2f   CPL    ",0
	.a30 db "0x30   JR     NC, 0x%02x",0
	.a31 db "0x31   LD     SP, 0x%02x%02x",0
	.a32 db "0x32   LD     (HL-), A",0
	.a33 db "0x33   INC    SP",0
	.a34 db "0x34   INC    (HL)",0
	.a35 db "0x35   DEC    (HL)",0
	.a36 db "0x36   LD     (HL), 0x%02x",0
	.a37 db "0x37   SCF    ",0
	.a38 db "0x38   JR     C, 0x%02x",0
	.a39 db "0x39   ADD    HL, SP",0
	.a3a db "0x3a   LD     A, (HL-)",0
	.a3b db "0x3b   DEC    SP",0
	.a3c db "0x3c   INC    A",0
	.a3d db "0x3d   DEC    A",0
	.a3e db "0x3e   LD     A, 0x%02x",0
	.a3f db "0x3f   CCF    ",0
	.a40 db "0x40   LD     B, B",0
	.a41 db "0x41   LD     B, C",0
	.a42 db "0x42   LD     B, D",0
	.a43 db "0x43   LD     B, E",0
	.a44 db "0x44   LD     B, H",0
	.a45 db "0x45   LD     B, L",0
	.a46 db "0x46   LD     B, (HL)",0
	.a47 db "0x47   LD     B, A",0
	.a48 db "0x48   LD     C, B",0
	.a49 db "0x49   LD     C, C",0
	.a4a db "0x4a   LD     C, D",0
	.a4b db "0x4b   LD     C, E",0
	.a4c db "0x4c   LD     C, H",0
	.a4d db "0x4d   LD     C, L",0
	.a4e db "0x4e   LD     C, (HL)",0
	.a4f db "0x4f   LD     C, A",0
	.a50 db "0x50   LD     D, B",0
	.a51 db "0x51   LD     D, C",0
	.a52 db "0x52   LD     D, D",0
	.a53 db "0x53   LD     D, E",0
	.a54 db "0x54   LD     D, H",0
	.a55 db "0x55   LD     D, L",0
	.a56 db "0x56   LD     D, (HL)",0
	.a57 db "0x57   LD     D, A",0
	.a58 db "0x58   LD     E, B",0
	.a59 db "0x59   LD     E, C",0
	.a5a db "0x5a   LD     E, D",0
	.a5b db "0x5b   LD     E, E",0
	.a5c db "0x5c   LD     E, H",0
	.a5d db "0x5d   LD     E, L",0
	.a5e db "0x5e   LD     E, (HL)",0
	.a5f db "0x5f   LD     E, A",0
	.a60 db "0x60   LD     H, B",0
	.a61 db "0x61   LD     H, C",0
	.a62 db "0x62   LD     H, D",0
	.a63 db "0x63   LD     H, E",0
	.a64 db "0x64   LD     H, H",0
	.a65 db "0x65   LD     H, L",0
	.a66 db "0x66   LD     H, (HL)",0
	.a67 db "0x67   LD     H, A",0
	.a68 db "0x68   LD     L, B",0
	.a69 db "0x69   LD     L, C",0
	.a6a db "0x6a   LD     L, D",0
	.a6b db "0x6b   LD     L, E",0
	.a6c db "0x6c   LD     L, H",0
	.a6d db "0x6d   LD     L, L",0
	.a6e db "0x6e   LD     L, (HL)",0
	.a6f db "0x6f   LD     L, A",0
	.a70 db "0x70   LD     (HL), B",0
	.a71 db "0x71   LD     (HL), C",0
	.a72 db "0x72   LD     (HL), D",0
	.a73 db "0x73   LD     (HL), E",0
	.a74 db "0x74   LD     (HL), H",0
	.a75 db "0x75   LD     (HL), L",0
	.a76 db "0x76   HALT   ",0
	.a77 db "0x77   LD     (HL), A",0
	.a78 db "0x78   LD     A, B",0
	.a79 db "0x79   LD     A, C",0
	.a7a db "0x7a   LD     A, D",0
	.a7b db "0x7b   LD     A, E",0
	.a7c db "0x7c   LD     A, H",0
	.a7d db "0x7d   LD     A, L",0
	.a7e db "0x7e   LD     A, (HL)",0
	.a7f db "0x7f   LD     A, A",0
	.a80 db "0x80   ADD    A, B",0
	.a81 db "0x81   ADD    A, C",0
	.a82 db "0x82   ADD    A, D",0
	.a83 db "0x83   ADD    A, E",0
	.a84 db "0x84   ADD    A, H",0
	.a85 db "0x85   ADD    A, L",0
	.a86 db "0x86   ADD    A, (HL)",0
	.a87 db "0x87   ADD    A, A",0
	.a88 db "0x88   ADC    A, B",0
	.a89 db "0x89   ADC    A, C",0
	.a8a db "0x8a   ADC    A, D",0
	.a8b db "0x8b   ADC    A, E",0
	.a8c db "0x8c   ADC    A, H",0
	.a8d db "0x8d   ADC    A, L",0
	.a8e db "0x8e   ADC    A, (HL)",0
	.a8f db "0x8f   ADC    A, A",0
	.a90 db "0x90   SUB    B",0
	.a91 db "0x91   SUB    C",0
	.a92 db "0x92   SUB    D",0
	.a93 db "0x93   SUB    E",0
	.a94 db "0x94   SUB    H",0
	.a95 db "0x95   SUB    L",0
	.a96 db "0x96   SUB    (HL)",0
	.a97 db "0x97   SUB    A",0
	.a98 db "0x98   SBC    A, B",0
	.a99 db "0x99   SBC    A, C",0
	.a9a db "0x9a   SBC    A, D",0
	.a9b db "0x9b   SBC    A, E",0
	.a9c db "0x9c   SBC    A, H",0
	.a9d db "0x9d   SBC    A, L",0
	.a9e db "0x9e   SBC    A, (HL)",0
	.a9f db "0x9f   SBC    A, A",0
	.aa0 db "0xa0   AND    B",0
	.aa1 db "0xa1   AND    C",0
	.aa2 db "0xa2   AND    D",0
	.aa3 db "0xa3   AND    E",0
	.aa4 db "0xa4   AND    H",0
	.aa5 db "0xa5   AND    L",0
	.aa6 db "0xa6   AND    (HL)",0
	.aa7 db "0xa7   AND    A",0
	.aa8 db "0xa8   XOR    B",0
	.aa9 db "0xa9   XOR    C",0
	.aaa db "0xaa   XOR    D",0
	.aab db "0xab   XOR    E",0
	.aac db "0xac   XOR    H",0
	.aad db "0xad   XOR    L",0
	.aae db "0xae   XOR    (HL)",0
	.aaf db "0xaf   XOR    A",0
	.ab0 db "0xb0   OR     B",0
	.ab1 db "0xb1   OR     C",0
	.ab2 db "0xb2   OR     D",0
	.ab3 db "0xb3   OR     E",0
	.ab4 db "0xb4   OR     H",0
	.ab5 db "0xb5   OR     L",0
	.ab6 db "0xb6   OR     (HL)",0
	.ab7 db "0xb7   OR     A",0
	.ab8 db "0xb8   CP     B",0
	.ab9 db "0xb9   CP     C",0
	.aba db "0xba   CP     D",0
	.abb db "0xbb   CP     E",0
	.abc db "0xbc   CP     H",0
	.abd db "0xbd   CP     L",0
	.abe db "0xbe   CP     (HL)",0
	.abf db "0xbf   CP     A",0
	.ac0 db "0xc0   RET    NZ",0
	.ac1 db "0xc1   POP    BC",0
	.ac2 db "0xc2   JP     NZ, 0x%02x%02x",0
	.ac3 db "0xc3   JP     0x%02x%02x",0
	.ac4 db "0xc4   CALL   NZ, 0x%02x%02x",0
	.ac5 db "0xc5   PUSH   BC",0
	.ac6 db "0xc6   ADD    A, 0x%02x",0
	.ac7 db "0xc7   RST    00H",0
	.ac8 db "0xc8   RET    Z",0
	.ac9 db "0xc9   RET    ",0
	.aca db "0xca   JP     Z, 0x%02x%02x",0
	.acc db "0xcc   CALL   Z, 0x%02x%02x",0
	.acd db "0xcd   CALL   0x%02x%02x",0
	.ace db "0xce   ADC    A, 0x%02x",0
	.acf db "0xcf   RST    08H",0
	.ad0 db "0xd0   RET    NC",0
	.ad1 db "0xd1   POP    DE",0
	.ad2 db "0xd2   JP     NC, 0x%02x%02x",0
	.ad3 db "0xd3   invalid  ",0
	.ad4 db "0xd4   CALL   NC, 0x%02x%02x",0
	.ad5 db "0xd5   PUSH   DE",0
	.ad6 db "0xd6   SUB    0x%02x",0
	.ad7 db "0xd7   RST    10H",0
	.ad8 db "0xd8   RET    C",0
	.ad9 db "0xd9   RETI   ",0
	.ada db "0xda   JP     C, 0x%02x%02x",0
	.adb db "0xdb   invalid  ",0
	.adc db "0xdc   CALL   C, 0x%02x%02x",0
	.add db "0xdd   invalid  ",0
	.ade db "0xde   SBC    A, 0x%02x",0
	.adf db "0xdf   RST    18H",0
	.ae0 db "0xe0   LDH    (0x%02x), A",0
	.ae1 db "0xe1   POP    HL",0
	.ae2 db "0xe2   LD     (C), A",0
	.ae3 db "0xe3   invalid  ",0
	.ae4 db "0xe4   invalid  ",0
	.ae5 db "0xe5   PUSH   HL",0
	.ae6 db "0xe6   AND    0x%02x",0
	.ae7 db "0xe7   RST    20H",0
	.ae8 db "0xe8   ADD    SP, 0x%02x",0
	.ae9 db "0xe9   JP     (HL)",0
	.aea db "0xea   LD     (0x%02x%02x), A",0
	.aeb db "0xeb   invalid  ",0
	.aec db "0xec   invalid  ",0
	.aed db "0xed   invalid  ",0
	.aee db "0xee   XOR    0x%02x",0
	.aef db "0xef   RST    28H",0
	.af0 db "0xf0   LDH    A, (0x%02x)",0
	.af1 db "0xf1   POP    AF",0
	.af2 db "0xf2   LD     A, (C)",0
	.af3 db "0xf3   DI     ",0
	.af4 db "0xf4   invalid  ",0
	.af5 db "0xf5   PUSH   AF",0
	.af6 db "0xf6   OR     0x%02x",0
	.af7 db "0xf7   RST    30H",0
	.af8 db "0xf8   LD     HL, SP+0x%02x",0
	.af9 db "0xf9   LD     SP, HL",0
	.afa db "0xfa   LD     A, (0x%02x%02x)",0
	.afb db "0xfb   EI     ",0
	.afc db "0xfc   invalid  ",0
	.afd db "0xfd   invalid  ",0
	.afe db "0xfe   CP     0x%02x",0
	.aff db "0xff   RST    38H",0
	
	; opcode with prefix 0xCB strings
	.b00 db "0xcb00 RLC    B",0
	.b01 db "0xcb01 RLC    C",0
	.b02 db "0xcb02 RLC    D",0
	.b03 db "0xcb03 RLC    E",0
	.b04 db "0xcb04 RLC    H",0
	.b05 db "0xcb05 RLC    L",0
	.b06 db "0xcb06 RLC    (HL)",0
	.b07 db "0xcb07 RLC    A",0
	.b08 db "0xcb08 RRC    B",0
	.b09 db "0xcb09 RRC    C",0
	.b0a db "0xcb0a RRC    D",0
	.b0b db "0xcb0b RRC    E",0
	.b0c db "0xcb0c RRC    H",0
	.b0d db "0xcb0d RRC    L",0
	.b0e db "0xcb0e RRC    (HL)",0
	.b0f db "0xcb0f RRC    A",0
	.b10 db "0xcb10 RL     B",0
	.b11 db "0xcb11 RL     C",0
	.b12 db "0xcb12 RL     D",0
	.b13 db "0xcb13 RL     E",0
	.b14 db "0xcb14 RL     H",0
	.b15 db "0xcb15 RL     L",0
	.b16 db "0xcb16 RL     (HL)",0
	.b17 db "0xcb17 RL     A",0
	.b18 db "0xcb18 RR     B",0
	.b19 db "0xcb19 RR     C",0
	.b1a db "0xcb1a RR     D",0
	.b1b db "0xcb1b RR     E",0
	.b1c db "0xcb1c RR     H",0
	.b1d db "0xcb1d RR     L",0
	.b1e db "0xcb1e RR     (HL)",0
	.b1f db "0xcb1f RR     A",0
	.b20 db "0xcb20 SLA    B",0
	.b21 db "0xcb21 SLA    C",0
	.b22 db "0xcb22 SLA    D",0
	.b23 db "0xcb23 SLA    E",0
	.b24 db "0xcb24 SLA    H",0
	.b25 db "0xcb25 SLA    L",0
	.b26 db "0xcb26 SLA    (HL)",0
	.b27 db "0xcb27 SLA    A",0
	.b28 db "0xcb28 SRA    B",0
	.b29 db "0xcb29 SRA    C",0
	.b2a db "0xcb2a SRA    D",0
	.b2b db "0xcb2b SRA    E",0
	.b2c db "0xcb2c SRA    H",0
	.b2d db "0xcb2d SRA    L",0
	.b2e db "0xcb2e SRA    (HL)",0
	.b2f db "0xcb2f SRA    A",0
	.b30 db "0xcb30 SWAP   B",0
	.b31 db "0xcb31 SWAP   C",0
	.b32 db "0xcb32 SWAP   D",0
	.b33 db "0xcb33 SWAP   E",0
	.b34 db "0xcb34 SWAP   H",0
	.b35 db "0xcb35 SWAP   L",0
	.b36 db "0xcb36 SWAP   (HL)",0
	.b37 db "0xcb37 SWAP   A",0
	.b38 db "0xcb38 SRL    B",0
	.b39 db "0xcb39 SRL    C",0
	.b3a db "0xcb3a SRL    D",0
	.b3b db "0xcb3b SRL    E",0
	.b3c db "0xcb3c SRL    H",0
	.b3d db "0xcb3d SRL    L",0
	.b3e db "0xcb3e SRL    (HL)",0
	.b3f db "0xcb3f SRL    A",0
	.b40 db "0xcb40 BIT    0, B",0
	.b41 db "0xcb41 BIT    0, C",0
	.b42 db "0xcb42 BIT    0, D",0
	.b43 db "0xcb43 BIT    0, E",0
	.b44 db "0xcb44 BIT    0, H",0
	.b45 db "0xcb45 BIT    0, L",0
	.b46 db "0xcb46 BIT    0, (HL)",0
	.b47 db "0xcb47 BIT    0, A",0
	.b48 db "0xcb48 BIT    1, B",0
	.b49 db "0xcb49 BIT    1, C",0
	.b4a db "0xcb4a BIT    1, D",0
	.b4b db "0xcb4b BIT    1, E",0
	.b4c db "0xcb4c BIT    1, H",0
	.b4d db "0xcb4d BIT    1, L",0
	.b4e db "0xcb4e BIT    1, (HL)",0
	.b4f db "0xcb4f BIT    1, A",0
	.b50 db "0xcb50 BIT    2, B",0
	.b51 db "0xcb51 BIT    2, C",0
	.b52 db "0xcb52 BIT    2, D",0
	.b53 db "0xcb53 BIT    2, E",0
	.b54 db "0xcb54 BIT    2, H",0
	.b55 db "0xcb55 BIT    2, L",0
	.b56 db "0xcb56 BIT    2, (HL)",0
	.b57 db "0xcb57 BIT    2, A",0
	.b58 db "0xcb58 BIT    3, B",0
	.b59 db "0xcb59 BIT    3, C",0
	.b5a db "0xcb5a BIT    3, D",0
	.b5b db "0xcb5b BIT    3, E",0
	.b5c db "0xcb5c BIT    3, H",0
	.b5d db "0xcb5d BIT    3, L",0
	.b5e db "0xcb5e BIT    3, (HL)",0
	.b5f db "0xcb5f BIT    3, A",0
	.b60 db "0xcb60 BIT    4, B",0
	.b61 db "0xcb61 BIT    4, C",0
	.b62 db "0xcb62 BIT    4, D",0
	.b63 db "0xcb63 BIT    4, E",0
	.b64 db "0xcb64 BIT    4, H",0
	.b65 db "0xcb65 BIT    4, L",0
	.b66 db "0xcb66 BIT    4, (HL)",0
	.b67 db "0xcb67 BIT    4, A",0
	.b68 db "0xcb68 BIT    5, B",0
	.b69 db "0xcb69 BIT    5, C",0
	.b6a db "0xcb6a BIT    5, D",0
	.b6b db "0xcb6b BIT    5, E",0
	.b6c db "0xcb6c BIT    5, H",0
	.b6d db "0xcb6d BIT    5, L",0
	.b6e db "0xcb6e BIT    5, (HL)",0
	.b6f db "0xcb6f BIT    5, A",0
	.b70 db "0xcb70 BIT    6, B",0
	.b71 db "0xcb71 BIT    6, C",0
	.b72 db "0xcb72 BIT    6, D",0
	.b73 db "0xcb73 BIT    6, E",0
	.b74 db "0xcb74 BIT    6, H",0
	.b75 db "0xcb75 BIT    6, L",0
	.b76 db "0xcb76 BIT    6, (HL)",0
	.b77 db "0xcb77 BIT    6, A",0
	.b78 db "0xcb78 BIT    7, B",0
	.b79 db "0xcb79 BIT    7, C",0
	.b7a db "0xcb7a BIT    7, D",0
	.b7b db "0xcb7b BIT    7, E",0
	.b7c db "0xcb7c BIT    7, H",0
	.b7d db "0xcb7d BIT    7, L",0
	.b7e db "0xcb7e BIT    7, (HL)",0
	.b7f db "0xcb7f BIT    7, A",0
	.b80 db "0xcb80 RES    0, B",0
	.b81 db "0xcb81 RES    0, C",0
	.b82 db "0xcb82 RES    0, D",0
	.b83 db "0xcb83 RES    0, E",0
	.b84 db "0xcb84 RES    0, H",0
	.b85 db "0xcb85 RES    0, L",0
	.b86 db "0xcb86 RES    0, (HL)",0
	.b87 db "0xcb87 RES    0, A",0
	.b88 db "0xcb88 RES    1, B",0
	.b89 db "0xcb89 RES    1, C",0
	.b8a db "0xcb8a RES    1, D",0
	.b8b db "0xcb8b RES    1, E",0
	.b8c db "0xcb8c RES    1, H",0
	.b8d db "0xcb8d RES    1, L",0
	.b8e db "0xcb8e RES    1, (HL)",0
	.b8f db "0xcb8f RES    1, A",0
	.b90 db "0xcb90 RES    2, B",0
	.b91 db "0xcb91 RES    2, C",0
	.b92 db "0xcb92 RES    2, D",0
	.b93 db "0xcb93 RES    2, E",0
	.b94 db "0xcb94 RES    2, H",0
	.b95 db "0xcb95 RES    2, L",0
	.b96 db "0xcb96 RES    2, (HL)",0
	.b97 db "0xcb97 RES    2, A",0
	.b98 db "0xcb98 RES    3, B",0
	.b99 db "0xcb99 RES    3, C",0
	.b9a db "0xcb9a RES    3, D",0
	.b9b db "0xcb9b RES    3, E",0
	.b9c db "0xcb9c RES    3, H",0
	.b9d db "0xcb9d RES    3, L",0
	.b9e db "0xcb9e RES    3, (HL)",0
	.b9f db "0xcb9f RES    3, A",0
	.ba0 db "0xcba0 RES    4, B",0
	.ba1 db "0xcba1 RES    4, C",0
	.ba2 db "0xcba2 RES    4, D",0
	.ba3 db "0xcba3 RES    4, E",0
	.ba4 db "0xcba4 RES    4, H",0
	.ba5 db "0xcba5 RES    4, L",0
	.ba6 db "0xcba6 RES    4, (HL)",0
	.ba7 db "0xcba7 RES    4, A",0
	.ba8 db "0xcba8 RES    5, B",0
	.ba9 db "0xcba9 RES    5, C",0
	.baa db "0xcbaa RES    5, D",0
	.bab db "0xcbab RES    5, E",0
	.bac db "0xcbac RES    5, H",0
	.bad db "0xcbad RES    5, L",0
	.bae db "0xcbae RES    5, (HL)",0
	.baf db "0xcbaf RES    5, A",0
	.bb0 db "0xcbb0 RES    6, B",0
	.bb1 db "0xcbb1 RES    6, C",0
	.bb2 db "0xcbb2 RES    6, D",0
	.bb3 db "0xcbb3 RES    6, E",0
	.bb4 db "0xcbb4 RES    6, H",0
	.bb5 db "0xcbb5 RES    6, L",0
	.bb6 db "0xcbb6 RES    6, (HL)",0
	.bb7 db "0xcbb7 RES    6, A",0
	.bb8 db "0xcbb8 RES    7, B",0
	.bb9 db "0xcbb9 RES    7, C",0
	.bba db "0xcbba RES    7, D",0
	.bbb db "0xcbbb RES    7, E",0
	.bbc db "0xcbbc RES    7, H",0
	.bbd db "0xcbbd RES    7, L",0
	.bbe db "0xcbbe RES    7, (HL)",0
	.bbf db "0xcbbf RES    7, A",0
	.bc0 db "0xcbc0 SET    0, B",0
	.bc1 db "0xcbc1 SET    0, C",0
	.bc2 db "0xcbc2 SET    0, D",0
	.bc3 db "0xcbc3 SET    0, E",0
	.bc4 db "0xcbc4 SET    0, H",0
	.bc5 db "0xcbc5 SET    0, L",0
	.bc6 db "0xcbc6 SET    0, (HL)",0
	.bc7 db "0xcbc7 SET    0, A",0
	.bc8 db "0xcbc8 SET    1, B",0
	.bc9 db "0xcbc9 SET    1, C",0
	.bca db "0xcbca SET    1, D",0
	.bcb db "0xcbcb SET    1, E",0
	.bcc db "0xcbcc SET    1, H",0
	.bcd db "0xcbcd SET    1, L",0
	.bce db "0xcbce SET    1, (HL)",0
	.bcf db "0xcbcf SET    1, A",0
	.bd0 db "0xcbd0 SET    2, B",0
	.bd1 db "0xcbd1 SET    2, C",0
	.bd2 db "0xcbd2 SET    2, D",0
	.bd3 db "0xcbd3 SET    2, E",0
	.bd4 db "0xcbd4 SET    2, H",0
	.bd5 db "0xcbd5 SET    2, L",0
	.bd6 db "0xcbd6 SET    2, (HL)",0
	.bd7 db "0xcbd7 SET    2, A",0
	.bd8 db "0xcbd8 SET    3, B",0
	.bd9 db "0xcbd9 SET    3, C",0
	.bda db "0xcbda SET    3, D",0
	.bdb db "0xcbdb SET    3, E",0
	.bdc db "0xcbdc SET    3, H",0
	.bdd db "0xcbdd SET    3, L",0
	.bde db "0xcbde SET    3, (HL)",0
	.bdf db "0xcbdf SET    3, A",0
	.be0 db "0xcbe0 SET    4, B",0
	.be1 db "0xcbe1 SET    4, C",0
	.be2 db "0xcbe2 SET    4, D",0
	.be3 db "0xcbe3 SET    4, E",0
	.be4 db "0xcbe4 SET    4, H",0
	.be5 db "0xcbe5 SET    4, L",0
	.be6 db "0xcbe6 SET    4, (HL)",0
	.be7 db "0xcbe7 SET    4, A",0
	.be8 db "0xcbe8 SET    5, B",0
	.be9 db "0xcbe9 SET    5, C",0
	.bea db "0xcbea SET    5, D",0
	.beb db "0xcbeb SET    5, E",0
	.bec db "0xcbec SET    5, H",0
	.bed db "0xcbed SET    5, L",0
	.bee db "0xcbee SET    5, (HL)",0
	.bef db "0xcbef SET    5, A",0
	.bf0 db "0xcbf0 SET    6, B",0
	.bf1 db "0xcbf1 SET    6, C",0
	.bf2 db "0xcbf2 SET    6, D",0
	.bf3 db "0xcbf3 SET    6, E",0
	.bf4 db "0xcbf4 SET    6, H",0
	.bf5 db "0xcbf5 SET    6, L",0
	.bf6 db "0xcbf6 SET    6, (HL)",0
	.bf7 db "0xcbf7 SET    6, A",0
	.bf8 db "0xcbf8 SET    7, B",0
	.bf9 db "0xcbf9 SET    7, C",0
	.bfa db "0xcbfa SET    7, D",0
	.bfb db "0xcbfb SET    7, E",0
	.bfc db "0xcbfc SET    7, H",0
	.bfd db "0xcbfd SET    7, L",0
	.bfe db "0xcbfe SET    7, (HL)",0
	.bff db "0xcbff SET    7, A",0
	