; This file is auto-generated by codegen. Don't modify it directly
; Either modify the opcode db or the generation logic in codegen
; These instructions are used by the disassembler (produced by -i)

	; opcode print instructions
@@:
	cmp		al, 0x00
	jne		@f
	push	.a00
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x01
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.a01
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0x02
	jne		@f
	push	.a02
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x03
	jne		@f
	push	.a03
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x04
	jne		@f
	push	.a04
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x05
	jne		@f
	push	.a05
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x06
	jne		@f
	push	dword[ebp+.param1]
	push	.a06
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x07
	jne		@f
	push	.a07
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x08
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.a08
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0x09
	jne		@f
	push	.a09
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x0a
	jne		@f
	push	.a0a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x0b
	jne		@f
	push	.a0b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x0c
	jne		@f
	push	.a0c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x0d
	jne		@f
	push	.a0d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x0e
	jne		@f
	push	dword[ebp+.param1]
	push	.a0e
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x0f
	jne		@f
	push	.a0f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x10
	jne		@f
	push	.a10
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x11
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.a11
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0x12
	jne		@f
	push	.a12
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x13
	jne		@f
	push	.a13
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x14
	jne		@f
	push	.a14
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x15
	jne		@f
	push	.a15
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x16
	jne		@f
	push	dword[ebp+.param1]
	push	.a16
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x17
	jne		@f
	push	.a17
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x18
	jne		@f
	push	dword[ebp+.param1]
	push	.a18
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x19
	jne		@f
	push	.a19
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x1a
	jne		@f
	push	.a1a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x1b
	jne		@f
	push	.a1b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x1c
	jne		@f
	push	.a1c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x1d
	jne		@f
	push	.a1d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x1e
	jne		@f
	push	dword[ebp+.param1]
	push	.a1e
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x1f
	jne		@f
	push	.a1f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x20
	jne		@f
	push	dword[ebp+.param1]
	push	.a20
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x21
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.a21
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0x22
	jne		@f
	push	.a22
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x23
	jne		@f
	push	.a23
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x24
	jne		@f
	push	.a24
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x25
	jne		@f
	push	.a25
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x26
	jne		@f
	push	dword[ebp+.param1]
	push	.a26
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x27
	jne		@f
	push	.a27
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x28
	jne		@f
	push	dword[ebp+.param1]
	push	.a28
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x29
	jne		@f
	push	.a29
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x2a
	jne		@f
	push	.a2a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x2b
	jne		@f
	push	.a2b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x2c
	jne		@f
	push	.a2c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x2d
	jne		@f
	push	.a2d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x2e
	jne		@f
	push	dword[ebp+.param1]
	push	.a2e
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x2f
	jne		@f
	push	.a2f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x30
	jne		@f
	push	dword[ebp+.param1]
	push	.a30
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x31
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.a31
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0x32
	jne		@f
	push	.a32
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x33
	jne		@f
	push	.a33
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x34
	jne		@f
	push	.a34
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x35
	jne		@f
	push	.a35
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x36
	jne		@f
	push	dword[ebp+.param1]
	push	.a36
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x37
	jne		@f
	push	.a37
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x38
	jne		@f
	push	dword[ebp+.param1]
	push	.a38
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x39
	jne		@f
	push	.a39
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x3a
	jne		@f
	push	.a3a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x3b
	jne		@f
	push	.a3b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x3c
	jne		@f
	push	.a3c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x3d
	jne		@f
	push	.a3d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x3e
	jne		@f
	push	dword[ebp+.param1]
	push	.a3e
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x3f
	jne		@f
	push	.a3f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x40
	jne		@f
	push	.a40
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x41
	jne		@f
	push	.a41
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x42
	jne		@f
	push	.a42
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x43
	jne		@f
	push	.a43
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x44
	jne		@f
	push	.a44
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x45
	jne		@f
	push	.a45
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x46
	jne		@f
	push	.a46
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x47
	jne		@f
	push	.a47
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x48
	jne		@f
	push	.a48
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x49
	jne		@f
	push	.a49
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x4a
	jne		@f
	push	.a4a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x4b
	jne		@f
	push	.a4b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x4c
	jne		@f
	push	.a4c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x4d
	jne		@f
	push	.a4d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x4e
	jne		@f
	push	.a4e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x4f
	jne		@f
	push	.a4f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x50
	jne		@f
	push	.a50
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x51
	jne		@f
	push	.a51
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x52
	jne		@f
	push	.a52
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x53
	jne		@f
	push	.a53
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x54
	jne		@f
	push	.a54
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x55
	jne		@f
	push	.a55
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x56
	jne		@f
	push	.a56
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x57
	jne		@f
	push	.a57
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x58
	jne		@f
	push	.a58
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x59
	jne		@f
	push	.a59
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x5a
	jne		@f
	push	.a5a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x5b
	jne		@f
	push	.a5b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x5c
	jne		@f
	push	.a5c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x5d
	jne		@f
	push	.a5d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x5e
	jne		@f
	push	.a5e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x5f
	jne		@f
	push	.a5f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x60
	jne		@f
	push	.a60
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x61
	jne		@f
	push	.a61
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x62
	jne		@f
	push	.a62
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x63
	jne		@f
	push	.a63
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x64
	jne		@f
	push	.a64
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x65
	jne		@f
	push	.a65
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x66
	jne		@f
	push	.a66
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x67
	jne		@f
	push	.a67
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x68
	jne		@f
	push	.a68
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x69
	jne		@f
	push	.a69
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x6a
	jne		@f
	push	.a6a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x6b
	jne		@f
	push	.a6b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x6c
	jne		@f
	push	.a6c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x6d
	jne		@f
	push	.a6d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x6e
	jne		@f
	push	.a6e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x6f
	jne		@f
	push	.a6f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x70
	jne		@f
	push	.a70
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x71
	jne		@f
	push	.a71
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x72
	jne		@f
	push	.a72
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x73
	jne		@f
	push	.a73
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x74
	jne		@f
	push	.a74
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x75
	jne		@f
	push	.a75
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x76
	jne		@f
	push	.a76
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x77
	jne		@f
	push	.a77
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x78
	jne		@f
	push	.a78
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x79
	jne		@f
	push	.a79
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x7a
	jne		@f
	push	.a7a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x7b
	jne		@f
	push	.a7b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x7c
	jne		@f
	push	.a7c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x7d
	jne		@f
	push	.a7d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x7e
	jne		@f
	push	.a7e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x7f
	jne		@f
	push	.a7f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x80
	jne		@f
	push	.a80
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x81
	jne		@f
	push	.a81
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x82
	jne		@f
	push	.a82
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x83
	jne		@f
	push	.a83
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x84
	jne		@f
	push	.a84
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x85
	jne		@f
	push	.a85
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x86
	jne		@f
	push	.a86
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x87
	jne		@f
	push	.a87
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x88
	jne		@f
	push	.a88
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x89
	jne		@f
	push	.a89
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x8a
	jne		@f
	push	.a8a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x8b
	jne		@f
	push	.a8b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x8c
	jne		@f
	push	.a8c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x8d
	jne		@f
	push	.a8d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x8e
	jne		@f
	push	.a8e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x8f
	jne		@f
	push	.a8f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x90
	jne		@f
	push	.a90
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x91
	jne		@f
	push	.a91
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x92
	jne		@f
	push	.a92
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x93
	jne		@f
	push	.a93
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x94
	jne		@f
	push	.a94
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x95
	jne		@f
	push	.a95
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x96
	jne		@f
	push	.a96
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x97
	jne		@f
	push	.a97
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x98
	jne		@f
	push	.a98
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x99
	jne		@f
	push	.a99
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x9a
	jne		@f
	push	.a9a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x9b
	jne		@f
	push	.a9b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x9c
	jne		@f
	push	.a9c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x9d
	jne		@f
	push	.a9d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x9e
	jne		@f
	push	.a9e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0x9f
	jne		@f
	push	.a9f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa0
	jne		@f
	push	.aa0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa1
	jne		@f
	push	.aa1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa2
	jne		@f
	push	.aa2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa3
	jne		@f
	push	.aa3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa4
	jne		@f
	push	.aa4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa5
	jne		@f
	push	.aa5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa6
	jne		@f
	push	.aa6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa7
	jne		@f
	push	.aa7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa8
	jne		@f
	push	.aa8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xa9
	jne		@f
	push	.aa9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xaa
	jne		@f
	push	.aaa
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xab
	jne		@f
	push	.aab
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xac
	jne		@f
	push	.aac
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xad
	jne		@f
	push	.aad
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xae
	jne		@f
	push	.aae
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xaf
	jne		@f
	push	.aaf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb0
	jne		@f
	push	.ab0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb1
	jne		@f
	push	.ab1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb2
	jne		@f
	push	.ab2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb3
	jne		@f
	push	.ab3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb4
	jne		@f
	push	.ab4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb5
	jne		@f
	push	.ab5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb6
	jne		@f
	push	.ab6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb7
	jne		@f
	push	.ab7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb8
	jne		@f
	push	.ab8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xb9
	jne		@f
	push	.ab9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xba
	jne		@f
	push	.aba
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xbb
	jne		@f
	push	.abb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xbc
	jne		@f
	push	.abc
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xbd
	jne		@f
	push	.abd
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xbe
	jne		@f
	push	.abe
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xbf
	jne		@f
	push	.abf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xc0
	jne		@f
	push	.ac0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xc1
	jne		@f
	push	.ac1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xc2
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.ac2
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xc3
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.ac3
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xc4
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.ac4
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xc5
	jne		@f
	push	.ac5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xc6
	jne		@f
	push	dword[ebp+.param1]
	push	.ac6
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc7
	jne		@f
	push	.ac7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xc8
	jne		@f
	push	.ac8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xc9
	jne		@f
	push	.ac9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xca
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.aca
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xcc
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.acc
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xcd
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.acd
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xce
	jne		@f
	push	dword[ebp+.param1]
	push	.ace
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xcf
	jne		@f
	push	.acf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xd0
	jne		@f
	push	.ad0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xd1
	jne		@f
	push	.ad1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xd2
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.ad2
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xd3
	jne		@f
	push	.ad3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xd4
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.ad4
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xd5
	jne		@f
	push	.ad5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xd6
	jne		@f
	push	dword[ebp+.param1]
	push	.ad6
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd7
	jne		@f
	push	.ad7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xd8
	jne		@f
	push	.ad8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xd9
	jne		@f
	push	.ad9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xda
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.ada
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xdb
	jne		@f
	push	.adb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xdc
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.adc
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xdd
	jne		@f
	push	.add
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xde
	jne		@f
	push	dword[ebp+.param1]
	push	.ade
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xdf
	jne		@f
	push	.adf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xe0
	jne		@f
	push	dword[ebp+.param1]
	push	.ae0
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe1
	jne		@f
	push	.ae1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xe2
	jne		@f
	push	.ae2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xe3
	jne		@f
	push	.ae3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xe4
	jne		@f
	push	.ae4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xe5
	jne		@f
	push	.ae5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xe6
	jne		@f
	push	dword[ebp+.param1]
	push	.ae6
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe7
	jne		@f
	push	.ae7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xe8
	jne		@f
	push	dword[ebp+.param1]
	push	.ae8
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe9
	jne		@f
	push	.ae9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xea
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.aea
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xeb
	jne		@f
	push	.aeb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xec
	jne		@f
	push	.aec
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xed
	jne		@f
	push	.aed
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xee
	jne		@f
	push	dword[ebp+.param1]
	push	.aee
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xef
	jne		@f
	push	.aef
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xf0
	jne		@f
	push	dword[ebp+.param1]
	push	.af0
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf1
	jne		@f
	push	.af1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xf2
	jne		@f
	push	.af2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xf3
	jne		@f
	push	.af3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xf4
	jne		@f
	push	.af4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xf5
	jne		@f
	push	.af5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xf6
	jne		@f
	push	dword[ebp+.param1]
	push	.af6
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf7
	jne		@f
	push	.af7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xf8
	jne		@f
	push	dword[ebp+.param1]
	push	.af8
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf9
	jne		@f
	push	.af9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xfa
	jne		@f
	push	dword[ebp+.param1]
	push	dword[ebp+.param2]
	push	.afa
	call	[printf]
	add		esp, 4*3
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 3
	jmp		.exit
@@:
	cmp		al, 0xfb
	jne		@f
	push	.afb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xfc
	jne		@f
	push	.afc
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xfd
	jne		@f
	push	.afd
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit
@@:
	cmp		al, 0xfe
	jne		@f
	push	dword[ebp+.param1]
	push	.afe
	call	[printf]
	add		esp, 4*2
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xff
	jne		@f
	push	.aff
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 1
	jmp		.exit

	; opcode (with prefix 0xCB) print instructions
.cb_ops:
@@:
	cmp		al, 0x00
	jne		@f
	push	.b00
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x01
	jne		@f
	push	.b01
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x02
	jne		@f
	push	.b02
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x03
	jne		@f
	push	.b03
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x04
	jne		@f
	push	.b04
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x05
	jne		@f
	push	.b05
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x06
	jne		@f
	push	.b06
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x07
	jne		@f
	push	.b07
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x08
	jne		@f
	push	.b08
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x09
	jne		@f
	push	.b09
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x0a
	jne		@f
	push	.b0a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x0b
	jne		@f
	push	.b0b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x0c
	jne		@f
	push	.b0c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x0d
	jne		@f
	push	.b0d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x0e
	jne		@f
	push	.b0e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x0f
	jne		@f
	push	.b0f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x10
	jne		@f
	push	.b10
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x11
	jne		@f
	push	.b11
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x12
	jne		@f
	push	.b12
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x13
	jne		@f
	push	.b13
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x14
	jne		@f
	push	.b14
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x15
	jne		@f
	push	.b15
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x16
	jne		@f
	push	.b16
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x17
	jne		@f
	push	.b17
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x18
	jne		@f
	push	.b18
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x19
	jne		@f
	push	.b19
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x1a
	jne		@f
	push	.b1a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x1b
	jne		@f
	push	.b1b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x1c
	jne		@f
	push	.b1c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x1d
	jne		@f
	push	.b1d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x1e
	jne		@f
	push	.b1e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x1f
	jne		@f
	push	.b1f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x20
	jne		@f
	push	.b20
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x21
	jne		@f
	push	.b21
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x22
	jne		@f
	push	.b22
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x23
	jne		@f
	push	.b23
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x24
	jne		@f
	push	.b24
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x25
	jne		@f
	push	.b25
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x26
	jne		@f
	push	.b26
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x27
	jne		@f
	push	.b27
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x28
	jne		@f
	push	.b28
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x29
	jne		@f
	push	.b29
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x2a
	jne		@f
	push	.b2a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x2b
	jne		@f
	push	.b2b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x2c
	jne		@f
	push	.b2c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x2d
	jne		@f
	push	.b2d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x2e
	jne		@f
	push	.b2e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x2f
	jne		@f
	push	.b2f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x30
	jne		@f
	push	.b30
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x31
	jne		@f
	push	.b31
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x32
	jne		@f
	push	.b32
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x33
	jne		@f
	push	.b33
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x34
	jne		@f
	push	.b34
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x35
	jne		@f
	push	.b35
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x36
	jne		@f
	push	.b36
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x37
	jne		@f
	push	.b37
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x38
	jne		@f
	push	.b38
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x39
	jne		@f
	push	.b39
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x3a
	jne		@f
	push	.b3a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x3b
	jne		@f
	push	.b3b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x3c
	jne		@f
	push	.b3c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x3d
	jne		@f
	push	.b3d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x3e
	jne		@f
	push	.b3e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x3f
	jne		@f
	push	.b3f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x40
	jne		@f
	push	.b40
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x41
	jne		@f
	push	.b41
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x42
	jne		@f
	push	.b42
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x43
	jne		@f
	push	.b43
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x44
	jne		@f
	push	.b44
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x45
	jne		@f
	push	.b45
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x46
	jne		@f
	push	.b46
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x47
	jne		@f
	push	.b47
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x48
	jne		@f
	push	.b48
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x49
	jne		@f
	push	.b49
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x4a
	jne		@f
	push	.b4a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x4b
	jne		@f
	push	.b4b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x4c
	jne		@f
	push	.b4c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x4d
	jne		@f
	push	.b4d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x4e
	jne		@f
	push	.b4e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x4f
	jne		@f
	push	.b4f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x50
	jne		@f
	push	.b50
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x51
	jne		@f
	push	.b51
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x52
	jne		@f
	push	.b52
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x53
	jne		@f
	push	.b53
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x54
	jne		@f
	push	.b54
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x55
	jne		@f
	push	.b55
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x56
	jne		@f
	push	.b56
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x57
	jne		@f
	push	.b57
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x58
	jne		@f
	push	.b58
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x59
	jne		@f
	push	.b59
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x5a
	jne		@f
	push	.b5a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x5b
	jne		@f
	push	.b5b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x5c
	jne		@f
	push	.b5c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x5d
	jne		@f
	push	.b5d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x5e
	jne		@f
	push	.b5e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x5f
	jne		@f
	push	.b5f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x60
	jne		@f
	push	.b60
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x61
	jne		@f
	push	.b61
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x62
	jne		@f
	push	.b62
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x63
	jne		@f
	push	.b63
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x64
	jne		@f
	push	.b64
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x65
	jne		@f
	push	.b65
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x66
	jne		@f
	push	.b66
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x67
	jne		@f
	push	.b67
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x68
	jne		@f
	push	.b68
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x69
	jne		@f
	push	.b69
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x6a
	jne		@f
	push	.b6a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x6b
	jne		@f
	push	.b6b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x6c
	jne		@f
	push	.b6c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x6d
	jne		@f
	push	.b6d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x6e
	jne		@f
	push	.b6e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x6f
	jne		@f
	push	.b6f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x70
	jne		@f
	push	.b70
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x71
	jne		@f
	push	.b71
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x72
	jne		@f
	push	.b72
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x73
	jne		@f
	push	.b73
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x74
	jne		@f
	push	.b74
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x75
	jne		@f
	push	.b75
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x76
	jne		@f
	push	.b76
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x77
	jne		@f
	push	.b77
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x78
	jne		@f
	push	.b78
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x79
	jne		@f
	push	.b79
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x7a
	jne		@f
	push	.b7a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x7b
	jne		@f
	push	.b7b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x7c
	jne		@f
	push	.b7c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x7d
	jne		@f
	push	.b7d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x7e
	jne		@f
	push	.b7e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x7f
	jne		@f
	push	.b7f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x80
	jne		@f
	push	.b80
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x81
	jne		@f
	push	.b81
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x82
	jne		@f
	push	.b82
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x83
	jne		@f
	push	.b83
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x84
	jne		@f
	push	.b84
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x85
	jne		@f
	push	.b85
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x86
	jne		@f
	push	.b86
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x87
	jne		@f
	push	.b87
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x88
	jne		@f
	push	.b88
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x89
	jne		@f
	push	.b89
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x8a
	jne		@f
	push	.b8a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x8b
	jne		@f
	push	.b8b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x8c
	jne		@f
	push	.b8c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x8d
	jne		@f
	push	.b8d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x8e
	jne		@f
	push	.b8e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x8f
	jne		@f
	push	.b8f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x90
	jne		@f
	push	.b90
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x91
	jne		@f
	push	.b91
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x92
	jne		@f
	push	.b92
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x93
	jne		@f
	push	.b93
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x94
	jne		@f
	push	.b94
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x95
	jne		@f
	push	.b95
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x96
	jne		@f
	push	.b96
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x97
	jne		@f
	push	.b97
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x98
	jne		@f
	push	.b98
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x99
	jne		@f
	push	.b99
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x9a
	jne		@f
	push	.b9a
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x9b
	jne		@f
	push	.b9b
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x9c
	jne		@f
	push	.b9c
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x9d
	jne		@f
	push	.b9d
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x9e
	jne		@f
	push	.b9e
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0x9f
	jne		@f
	push	.b9f
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa0
	jne		@f
	push	.ba0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa1
	jne		@f
	push	.ba1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa2
	jne		@f
	push	.ba2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa3
	jne		@f
	push	.ba3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa4
	jne		@f
	push	.ba4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa5
	jne		@f
	push	.ba5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa6
	jne		@f
	push	.ba6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa7
	jne		@f
	push	.ba7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa8
	jne		@f
	push	.ba8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xa9
	jne		@f
	push	.ba9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xaa
	jne		@f
	push	.baa
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xab
	jne		@f
	push	.bab
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xac
	jne		@f
	push	.bac
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xad
	jne		@f
	push	.bad
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xae
	jne		@f
	push	.bae
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xaf
	jne		@f
	push	.baf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb0
	jne		@f
	push	.bb0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb1
	jne		@f
	push	.bb1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb2
	jne		@f
	push	.bb2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb3
	jne		@f
	push	.bb3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb4
	jne		@f
	push	.bb4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb5
	jne		@f
	push	.bb5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb6
	jne		@f
	push	.bb6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb7
	jne		@f
	push	.bb7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb8
	jne		@f
	push	.bb8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xb9
	jne		@f
	push	.bb9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xba
	jne		@f
	push	.bba
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xbb
	jne		@f
	push	.bbb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xbc
	jne		@f
	push	.bbc
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xbd
	jne		@f
	push	.bbd
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xbe
	jne		@f
	push	.bbe
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xbf
	jne		@f
	push	.bbf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc0
	jne		@f
	push	.bc0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc1
	jne		@f
	push	.bc1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc2
	jne		@f
	push	.bc2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc3
	jne		@f
	push	.bc3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc4
	jne		@f
	push	.bc4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc5
	jne		@f
	push	.bc5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc6
	jne		@f
	push	.bc6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc7
	jne		@f
	push	.bc7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc8
	jne		@f
	push	.bc8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xc9
	jne		@f
	push	.bc9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xca
	jne		@f
	push	.bca
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xcb
	jne		@f
	push	.bcb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xcc
	jne		@f
	push	.bcc
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xcd
	jne		@f
	push	.bcd
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xce
	jne		@f
	push	.bce
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xcf
	jne		@f
	push	.bcf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd0
	jne		@f
	push	.bd0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd1
	jne		@f
	push	.bd1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd2
	jne		@f
	push	.bd2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd3
	jne		@f
	push	.bd3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd4
	jne		@f
	push	.bd4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd5
	jne		@f
	push	.bd5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd6
	jne		@f
	push	.bd6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd7
	jne		@f
	push	.bd7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd8
	jne		@f
	push	.bd8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xd9
	jne		@f
	push	.bd9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xda
	jne		@f
	push	.bda
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xdb
	jne		@f
	push	.bdb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xdc
	jne		@f
	push	.bdc
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xdd
	jne		@f
	push	.bdd
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xde
	jne		@f
	push	.bde
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xdf
	jne		@f
	push	.bdf
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe0
	jne		@f
	push	.be0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe1
	jne		@f
	push	.be1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe2
	jne		@f
	push	.be2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe3
	jne		@f
	push	.be3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe4
	jne		@f
	push	.be4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe5
	jne		@f
	push	.be5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe6
	jne		@f
	push	.be6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe7
	jne		@f
	push	.be7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe8
	jne		@f
	push	.be8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xe9
	jne		@f
	push	.be9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xea
	jne		@f
	push	.bea
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xeb
	jne		@f
	push	.beb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xec
	jne		@f
	push	.bec
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xed
	jne		@f
	push	.bed
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xee
	jne		@f
	push	.bee
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xef
	jne		@f
	push	.bef
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf0
	jne		@f
	push	.bf0
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf1
	jne		@f
	push	.bf1
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf2
	jne		@f
	push	.bf2
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf3
	jne		@f
	push	.bf3
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf4
	jne		@f
	push	.bf4
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf5
	jne		@f
	push	.bf5
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf6
	jne		@f
	push	.bf6
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf7
	jne		@f
	push	.bf7
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf8
	jne		@f
	push	.bf8
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xf9
	jne		@f
	push	.bf9
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xfa
	jne		@f
	push	.bfa
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xfb
	jne		@f
	push	.bfb
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xfc
	jne		@f
	push	.bfc
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xfd
	jne		@f
	push	.bfd
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xfe
	jne		@f
	push	.bfe
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
	cmp		al, 0xff
	jne		@f
	push	.bff
	call	[printf]
	add		esp, 4
	mov		esi, dword[ebp+.pc]
	add		dword[esi], 2
	jmp		.exit
@@:
.exit:
